service: bundlesize-service
frameworkVersion: '=1.26.1'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
  environment:
    LAMBDA_PREFIX: 'bundlesize-service-${opt:stage, self:provider.stage}-'

functions:
  # Endpoints
  keyword:
    handler: src/router.app
    events:
      - http:
          path: /
          method: get
